docs/source/installation.rst
plugins/modules/ims_command.py
plugins/modules/ims_dbd_gen.py
plugins/modules/ims_psb_gen.py

- Feature Pull Request
- New Module Pull Request
```paste below
```

Doc edits on ibm-zos-ims

---

docs/source/playbooks.rst
playbooks/ims-collection-sample.yaml

- Feature Pull Request
- New Module Pull Request
```paste below
```

Minor doc fixes in  the playbook and playbook.rst

---

README.md
docs/source/modules/ims_command.rst
plugins/modules/ims_command.py

Remove the original_command output field from IMS Command. 
ims_command as well as associated docs

remove original_command output

---

galaxy.yml

update galaxy.yml descriptions and typo in tags. 

update galaxy.yml description and typo in tags.

---

docs/zos-collection-index.rst

Updated zos-collection-index.rst with `source` path and removed the copyright since it will be shared content. 

Updated main zos-collection-index.rst with source path and removed shared content

---

docs/source/index.rst
docs/source/modules/ims_dbd_gen.rst
docs/source/modules/ims_psb_gen.rst
docs/source/requirements.rst
galaxy.yml
tests/run.sh

include new documentation for ims_dbd_gen and ims_psb_gen. 
updated index page and requirements page. 
- ims_dbd_gen
- ims_psb_gen
- general docs

Source doc updates

---

docs/source/modules/ims_acb_gen.rst

new source doc for acbgen module. 

new acbgen source rst.

---

README.md
docs/source/index.rst
galaxy.yml

Remove references to action plugins since the IMS collection no longer ships any. 

Remove action plugins

---

docs/source/conf.py
galaxy.yml

update release version. 
- Feature Pull Request

update references to point to 1.1.0-beta.1

---

docs/source/requirements_managed.rst

bugfix for space in notes documentation on requirements page. 

fix missing space in supported shell notes.

---

docs/templates/breadcrumbs.html

remove github edit option on top of doc pages. 

remove edit github link on top of doc pages.

---

playbook.sh
plugins/module_utils/ims_command_utils.py
plugins/modules/ims_command.py
tests/functional/modules/ims_command/create_query_delete/test_create_and_delete_pgm.py
tests/functional/modules/ims_command/create_query_delete/test_create_delete_tran.py
tests/functional/modules/ims_command/invalid_input/test_invalid_command.py
tests/functional/modules/ims_command/invalid_input/test_invalid_plex.py
tests/functional/modules/ims_command/invalid_input/test_invalid_route.py
tests/functional/modules/ims_command/misc_commands/test_special_characters.py
tests/functional/modules/ims_command/query/test_query_imsplex.py
tests/functional/modules/ims_command/query/test_query_pgm.py
tests/functional/modules/ims_command/query/test_query_tran.py
tests/functional/modules/ims_command/test_ims_command_sample.py
tests/functional/modules/ims_command/update/test_update_pgm.py
tests/functional/modules/ims_command/update/test_update_tran.py
tests/run.sh
tests/test_config.yml

updates to ims command module to support ansible-test sanity. 

Ims command sanity

---

tests/units/modules/ims_command/test_ims_command.py

Fixed anisble sanity test errors for the following folder
```
tests/units/modules/ims_command/
```

fixed sanity tests for ims_command unit tests

---

plugins/modules/ims_acb_gen.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.9.txt

acbgen import fixed for sanity

---

docs/ansible_content.rst

Remove non-existent plugins and filters references
Updates RST that is pointing to sources that don't exist. 

Remove non-existent references

---

docs/ansible_content.rst
docs/source/conf.py
docs/source/index.rst
docs/source/modules/ims_acb_gen.rst
docs/source/modules/ims_catalog_populate.rst
docs/source/modules/ims_catalog_purge.rst
docs/source/modules/ims_command.rst
docs/source/modules/ims_dbd_gen.rst
docs/source/modules/ims_dbrc.rst
docs/source/modules/ims_psb_gen.rst
docs/source/release_notes.rst
galaxy.yml
plugins/modules/ims_acb_gen.py
plugins/modules/ims_catalog_populate.py
plugins/modules/ims_catalog_purge.py
plugins/modules/ims_command.py
plugins/modules/ims_dbd_gen.py
plugins/modules/ims_dbrc.py
plugins/modules/ims_psb_gen.py

Version 1.1.0
====================
Notes
-----
* Update recommended
* Module changes
* ``ims_catalog_populate`` - improved pep8 and Ansible Sanity compliance
* ``ims_catalog_purge`` - improved pep8 and Ansible Sanity compliance
* ``ims_dbrc`` - improved pep8 and Ansible Sanity compliance
* ``ims_dbd_gen`` - added usage of Python tempdir libraries instead of fixed string
* ``ims_psb_gen`` - added usage of Python tempdir libraries instead of fixed string
* Documentation updates
* Improved test and security coverage
Availability
------------
* `Automation Hub`
* `Galaxy`
* `GitHub`
Reference
---------
* Supported by IBM z/OS core collection v1.2.1
* Supported by IBM Z Open Enterprise SDK for Python for z/OS: 3.8.2 or later
* Supported by IBM Z Open Automation Utilities 1.0.3 PTF UI70435
* …

Release v1.1.0

---

docs/source/conf.py

Signed-off-by: BRYANT PANYARACHUN <bpanyarachun@gmail.com>
Updating references to potentially offensive words that matter. 
configuration file used for doc generation. 
```

remove reference to whitelist.

---

CHANGELOG.rst
README.md
ansible.cfg
changelogs/changelog.yaml
changelogs/config.yaml
docs/source/release_notes.rst
galaxy.yml
meta/runtime.yml
plugins/modules/ims_catalog_populate.py
plugins/modules/ims_catalog_purge.py
tests/ansible.cfg
tests/conftest.py
tests/ims-collection-sample.yaml
tests/playbook.sh
tests/requirements.txt
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt
tests/sanity/ignore-2.13.txt
tests/sanity/ignore-2.14.txt
tests/sanity/ignore-2.9.txt
tests/test_config.yml

Release updates for 1.2.0 GA release

Dipti release v1.2 ga latest

---

docs/source/release_notes.rst

Add automation hub link to 1.2.0 release notes

add automation hub to release notes.

---

tests/functional/module_utils/ims_test_catalog_utils.py
tests/functional/modules/ims_catalog/test_catalog_invalid_input.py
tests/functional/modules/ims_catalog/test_catalog_valid_input.py

These files includes the test cases for the catalog module enhancements, there are 2 files, each for valid and invalid test cases of the functions
Test cases for Catalog
```paste below
```

Test catalog files

---

plugins/modules/ims_acb_gen.py

Updated the description and choices in the documentation in the `ims_acb_gen` module under the compression attirbute. 
Fixes #108 
`ims_acb_gen`
```paste below
```

change compression attribute description

---

docs/source/release_notes.rst

Update release notes documentation for 1.3.0-beta.1 release.
Docs Pull Request

Update release notes for 1.3.0-beta.1.

---

docs/source/community_guides.rst
docs/source/community_guides_docs/zos_ansible_module_testing.rst

add missing contribution pages 

add missing community guide docs
